import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LayoutProvider from "@/components/LayoutProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "relative h-[100dvh] font-sans antialiased bg-background p-4 lg:p-7 text-white"
        )}
      >
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
